# Generated by Django 5.1.1 on 2024-11-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_establecimiento_banner_establecimiento_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='coordenada_y',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
