# Generated by Django 5.1.1 on 2024-11-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_establecimiento_coordenada_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariosestablecimiento',
            old_name='dia',
            new_name='dia_semana',
        ),
        migrations.AlterUniqueTogether(
            name='horariosestablecimiento',
            unique_together={('establecimiento', 'dia_semana')},
        ),
    ]
