# Generated by Django 5.1.1 on 2024-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_dia_horariosestablecimiento_dia_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
