# Generated by Django 5.1.1 on 2024-11-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_establecimiento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario', unique=True),
        ),
    ]
