# Generated by Django 5.1.1 on 2024-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_establecimiento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_max',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
