# Generated by Django 5.1.1 on 2024-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_evento_precio_max_evento_precio_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='duenio',
            field=models.BooleanField(default=False),
        ),
    ]
