# Generated by Django 5.1.1 on 2024-11-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_usuario_duenio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='banner',
        ),
    ]
