# Generated by Django 5.1.1 on 2024-11-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_establecimiento_em_ref_alter_evento_precio_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
