# Generated by Django 5.1.1 on 2024-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_establecimiento_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galeriaestablecimiento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='galeriaestablecimiento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='galeriaestablecimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
