# Generated by Django 5.1.1 on 2024-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_galeriaestablecimiento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='interesados',
            field=models.IntegerField(default=0),
        ),
    ]
