# Generated by Django 5.1.1 on 2024-11-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_evento_interesados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='interesados',
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id_interes', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
