# Generated by Django 5.1.1 on 2024-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_evento_interesados_interes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionestablecimiento',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='valoracionevento',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
