# Generated by Django 5.1.1 on 2024-11-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_valoracionestablecimiento_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracionestablecimiento',
            name='id_visita_fk',
        ),
        migrations.RemoveField(
            model_name='valoracionevento',
            name='id_asistencia_fk',
        ),
        migrations.AddField(
            model_name='valoracionestablecimiento',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.establecimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracionestablecimiento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracionevento',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracionevento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
            preserve_default=False,
        ),
    ]
