# Generated by Django 5.1.1 on 2024-12-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_usuario_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='img_url',
        ),
        migrations.AddField(
            model_name='valoracionestablecimiento',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valoracionevento',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
