# Generated by Django 5.1.1 on 2024-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_usuario_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
