# Generated by Django 5.1.1 on 2024-12-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_usuario_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='img_url',
            new_name='imagen_url',
        ),
    ]
