# Generated by Django 5.1.1 on 2024-12-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_img_url_usuario_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
