# Generated by Django 5.1.1 on 2024-12-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_usuario_duenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etiqueta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
